// This class is automatically included in FastlaneRunner during build

// This autogenerated file will be overwritten or replaced when running "fastlane generate_swift"
//
//  ** NOTE **
//  This file is provided by fastlane and WILL be overwritten in future updates
//  If you want to add extra functionality to this project, create a new file in a
//  new group so that it won't be marked for upgrade
//

import Foundation

lane :beta do

  increment_build_number(xcodeproj: './DailyDiet.xcodeproj')
  gym(scheme: 'DailyDiet', workspace: './DailyDiet.xcworkspace')
  deliver(
    username: "aliireza12t@icloud.com",
    team_id: 'AJLMAG95WU',
    app_identifier: 'com.Alireza.Daily-Diet-X',
    submit_for_review: true,
    skip_metadata: true,
    skip_binary_upload: false,
    skip_screenshots: true,
    skip_app_version_update: false,
    force: true
  )
//  upload_to_testflight
end
