// This class is automatically included in FastlaneRunner during build

// This autogenerated file will be overwritten or replaced when running "fastlane generate_swift"
//
//  ** NOTE **
//  This file is provided by fastlane and WILL be overwritten in future updates
//  If you want to add extra functionality to this project, create a new file in a
//  new group so that it won't be marked for upgrade
//

import Foundation

lane :beta do

increment_build_number(xcodeproj: "./.xcodeproj")

sync_code_signing
disable_automatic_code_signing(path: "DailyDiet.xcworkspace")
build_app
enable_automatic_code_signing(path: "DailyDiet.xcworkspace")
upload_to_testflight
//  gym(scheme: "DailyDiet", workspace: "./DailyDiet.xcworkspace")
//  deliver(
//    username: "aliireza12t@icloud.com",
//    app_identifier: "com.Alireza.Daily-Diet-X",
//    submit_for_review: true,
//    skip_metadata: true,
//    skip_binary_upload: false,
//    skip_screenshots: true,
//    skip_app_version_update: false,
//    force: true
//  )
////  upload_to_testflight
end
