name: Deploying
on:
    push:
    branches:
        - master
jobs:
    deploy:
    name: Deploying to Testflight
    runs-on: macOS-latest
    steps:
        - name: Checkout repository
        uses: actions/checkout@v1
        - name: Install gpg
        run: brew install gnupg
        - name: Setup provisioning profile
        env:
            IOS_KEYS: ${{ secrets.IOS_KEYS }}
        run: ./secrets/decrypt_secrets.sh
        - name: Select Xcode
        run: sudo xcode-select -switch /Applications/Xcode_11.3.app
        - name: Xcode version
        run: /usr/bin/xcodebuild -version
        - name: Build archive
        run: ./scripts/archive_app.sh
        - name: Exporting .ipa
        run: ./scripts/export_ipa.sh
        - name: Publishing app
        if: success()
        env:
        APPLEID_USERNAME: ${{ secrets.APPLEID_USERNAME }}
        APPLEID_PASSWORD: ${{ secrets.APPLEID_PASSWORD }}
        run: ./scripts/publish_testflight.sh
