name: Deploy iOS to App Center

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v1
      
      - name: Install gpg
        run: brew install gnupg
        
      - name: Switch XCode Version
        run: sudo xcode-select -s /Applications/Xcode_11.2.app
        
      - name: Cache Pods dependencies
        uses: actions/cache@v1
        with:
          path: ios/Pods
          key: ${{ runner.OS }}-pods-cache-${{ hashFiles('**/Podfile.lock') }}
          restore-keys: |
            ${{ runner.OS }}-pods-cache-
      - name: Install pod dependencies
        run: |
          pod install
        shell: bash
      - name: Setup provisioning profile
        run: ./secrets/decrypt_secrets.sh
        env:
          IOS_PROFILE_KEY: ${{ secrets.IOS_PROFILE_KEY }}
      - name: Build app
        run: |
          cd xcodebuild archive \
            -workspace DailyDiet.xcworkspace \
            -scheme DailyDiet \
            -sdk iphoneos13.2 \
            -configuration Release \
            -archivePath $PWD/build/DailyDiet.xcarchive \
            IPHONEOS_DEPLOYMENT_TARGET=11.0
            PROVISIONING_PROFILE="DailyDiet/DailyDiet.entitlements" \
            CODE_SIGN_IDENTITY="iPhone Distribution: Aref Tarrah (AJLMAG95WU)"
      - name: Export app
        run: |
          cd xcodebuild \
            -exportArchive \
            -archivePath $PWD/build/DailyDiet.xcarchive \
            -exportOptionsPlist $PWD/ci.plist \
            -exportPath $PWD/build
      - name: Publishing app
        if: success()
        run: |
          xcrun altool --upload-app -t ios -f build/DailyDiet -u "${{ secrets.APPLEID_USERNAME }}" -p "${{ secrets.APPLEID_PASSWORD }}" --verbose
