name: Deploy iOS to App Center
 
on:
push:
  tags:
  - version*
 
jobs:
  build:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install and run xcodegen
      run: |
        brew install fastlane
    - name: Run fastlane setup
      env:
        APPLE_ACCOUNT: ${{ secrets.APPLEID_USERNAME }}
        TEAM_ID: ${{ secrets.TEAM_ID }}
      run: |
        export FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD="eprr-bwug-vfjd-ofxi"
        bundle exec fastlane beta --verbose
        
        
        
    
