name: Deploy iOS to App Center
 
on:
 push:
#   tags:
#   - version*
 
jobs:
  build:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install and run xcodegen
      run: |
        brew install fastlane
        # gem install bundler
        bundle install
    - name: Run fastlane setup
      env:
        APPLE_PASSWORD: ${{ secrets.APPLE_APPLICATION_SPECIFIC_PASSWORD }}
      run: |
       fastlane beta
#        export FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD="$APPLE_PASSWORD"
         
        
        
        
        
        
        

        
        




        
        
    
